#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
generate_lessons.py — எழுது
Generates exercise JSON files and updates data/lessons.json manifest.

Reads lesson_words.json (generated by add_words_to_lesson.py).

Usage:
    python3 generate_lessons.py
"""

import json
import os
import random

# ── Paths ─────────────────────────────────────────────────────────────────────
SCRIPT_DIR        = os.path.dirname(os.path.abspath(__file__))
EXERCISES_DIR     = os.path.join(SCRIPT_DIR, 'data', 'exercises')
LESSONS_FILE      = os.path.join(SCRIPT_DIR, 'data', 'lessons.json')
LESSON_WORDS_FILE = os.path.join(SCRIPT_DIR, 'lesson_words.json')
LESSON_PLAN_FILE  = os.path.join(SCRIPT_DIR, 'lesson_plan.json')

# ── Tamil character classification ────────────────────────────────────────────

def is_consonant(ch):
    """Tamil consonants: U+0B95–U+0BB9"""
    return '\u0B95' <= ch <= '\u0BB9'

def is_vowel(ch):
    """Tamil pure vowels: U+0B85–U+0B94"""
    return '\u0B85' <= ch <= '\u0B94'

# ── Vowel → marker mapping ────────────────────────────────────────────────────

VOWEL_TO_MARKER = {
    'அ': '',    # implicit — consonant alone carries அ sound
    'ஆ': 'ா',
    'இ': 'ி',
    'ஈ': 'ீ',
    'உ': 'ு',
    'ஊ': 'ூ',
    'எ': 'ெ',
    'ஏ': 'ே',
    'ஐ': 'ை',
    'ஒ': 'ொ',
    'ஓ': 'ோ',
    'ஔ': 'ௌ',
}

# Uyirmei vowel sequence (finger order on Tamil 99 keyboard)
UYIRMEI_VOWEL_ORDER = ['அ', '்', 'உ', 'இ', 'எ', 'ஐ', 'ஊ', 'ஈ', 'ஆ', 'ஏ', 'ஒ', 'ஓ', 'ஔ']

# ── Uyirmei helpers ───────────────────────────────────────────────────────────

def make_uyirmei_chars(consonant):
    """Generate all 13 uyirmei combinations for a consonant in finger order."""
    result = []
    for vowel in UYIRMEI_VOWEL_ORDER:
        if vowel == '்':
            result.append(consonant + '்')
        elif vowel == 'அ':
            result.append(consonant)
        else:
            result.append(consonant + VOWEL_TO_MARKER[vowel])
    return result

# ── Smart join ────────────────────────────────────────────────────────────────

def smart_join(chars, combination_mode):
    """
    Join chars into an exercise string.
    Non-combination: each character standalone, concatenated.
    Combination: consonant+vowel pairs pre-combined into uyirmei.
    """
    if not combination_mode:
        return ''.join(chars).strip()

    result = []
    i = 0
    while i < len(chars):
        ch = chars[i]
        if is_consonant(ch) and i + 1 < len(chars) and is_vowel(chars[i + 1]):
            result.append(ch + VOWEL_TO_MARKER.get(chars[i + 1], ''))
            i += 2
        else:
            result.append(ch)
            i += 1
    return ''.join(result).strip()

# ── Practice word generator (non-combo) ──────────────────────────────────────

def make_practice_words(pool, target=30):
    """
    Generate target words of 3–5 chars from pool.
    Returns a flat list of chars with spaces between words.
    """
    words = []

    # 1. Intro: 3-char repeated words (one per char in pool)
    intro = [ch * 3 for ch in pool]
    random.shuffle(intro)
    words += intro

    # 2. Progression: 3-4 char mixed words
    for i in range(len(pool)):
        c1 = pool[i]
        c2 = pool[(i + 1) % len(pool)]
        words += [c1 * 2 + c2, c2 + c1 * 2, c1 + c2 + c1 + c2]

    words = words[:target]

    # 3. Random 3-5 char words
    needed = max(target - len(words), 8)
    words += [''.join(random.choice(pool) for _ in range(random.randint(3, 5)))
              for _ in range(needed)]
    words = words[:target]

    # 4. Conclusion: 3-char patterned words
    conclusion = []
    for i in range(4):
        conclusion.append(pool[i % len(pool)] + pool[(i+1) % len(pool)] + pool[(i+2) % len(pool)])
    random.shuffle(conclusion)
    words += conclusion[:4]

    # Strict 3-5 char filter
    words = [w for w in words if 3 <= len(w) <= 5]
    while len(words) < target:
        w = ''.join(random.choice(pool) for _ in range(random.randint(3, 5)))
        if 3 <= len(w) <= 5:
            words.append(w)

    # Return as flat char list with spaces
    result = []
    for i, word in enumerate(words):
        result += list(word)
        if i < len(words) - 1:
            result.append(' ')
    return result

# ── Non-combo exercise generator ──────────────────────────────────────────────

def make_non_combo_exercises(chars, review_chars, lesson_id):
    """
    Generate exercises for a non-combination lesson.
    Ex 1-N : Introduction — one per new char, repeated
    Ex N+1 : Review — alternating patterns
    Ex N+2 : Review — with spaces
    Ex N+3 : Practice — random words from all chars
    """
    exercises     = []
    all_chars     = chars + review_chars
    practice_pool = [c for c in all_chars if c != ' ']

    if not chars:
        if len(practice_pool) >= 2:
            word_target = 25 + lesson_id // 2
            text = make_practice_words(practice_pool, target=word_target)
            exercises.append(smart_join(text, False))
        return exercises

    # Intro: one exercise per new char
    for ch in chars:
        exercises.append(smart_join([ch] * 2, False))

    # Review: alternating patterns (no spaces)
    if len(chars) >= 2:
        text = []
        for i in range(len(chars)):
            c1 = chars[i]; c2 = chars[(i + 1) % len(chars)]
            text += [c1]*4 + [c2]*4 + [c1]*2 + [c2]*2 + [c1, c2, c2, c1]
        exercises.append(smart_join(text, False))

        # Review with spaces
        text = []
        for ch in chars:
            text += ([ch] + [' ']) * 3
        for i in range(len(chars)):
            c1 = chars[i]; c2 = chars[(i+1) % len(chars)]
            text += [c1, c2, ' '] * 2
        exercises.append(smart_join(text, False))

    # Practice: random words from all chars
    if len(practice_pool) >= 2:
        word_target = 25 + lesson_id // 2
        text = make_practice_words(practice_pool, target=word_target)
        exercises.append(smart_join(text, False))

    return exercises

# ── Combo exercise generator ──────────────────────────────────────────────────

def max_words(chars):
    """N = 50 + (number of chars - 1) × 5"""
    return 50 + (len(chars) - 1) * 5

def make_combo_exercises(consonants, review_chars, words, lesson_id, has_words=True):
    """
    Generate exercises for a combination (uyirmei) lesson.

    Ex 1: Introduction — each uyirmei char twice with space (100%)
    Ex 2: Short words only, each repeated at least twice, fill to N (90%)
          Skipped if word_count == 0
    Ex 3: If words > N → all words (incl. sentences), no repeats, first N (80%)
          If words ≤ N → all words, randomized order, fill to N (80%)
          Skipped if word_count == 0
    """
    exercises = []
    words     = words or []
    N         = max_words(consonants)

    # Build uyirmei pool for all consonants in this lesson
    uyirmei_pool = []
    for consonant in consonants:
        uyirmei_pool += make_uyirmei_chars(consonant)

    # ── Ex 1: Introduction ────────────────────────────────────────────────────
    intro = []
    for ch in uyirmei_pool:
        intro += [ch, ' ', ch, ' ']
    exercises.append(''.join(intro).strip())

    if not has_words:
        return exercises  # no words — skip Ex 2 and Ex 3

    # ── Ex 2: Short words, each repeated at least twice ───────────────────────
    short_words = [w for w in words if ' ' not in w]
    ex2 = []
    if short_words:
        # Repeat each word at least twice
        for w in short_words:
            ex2 += [w, w]
        # Fill to N by repeating in shuffled order
        while len(ex2) < N:
            extra = list(short_words)
            random.shuffle(extra)
            ex2 += extra
        ex2 = ex2[:N]
    exercises.append(' '.join(ex2).strip())

    # ── Ex 3: All words (incl. sentences), fill to N, randomized ────────────
    if len(words) > N:
        # More words than N — take first N, no repeats
        ex3 = words[:N]
    else:
        # N or fewer words — randomize order and repeat until N reached
        ex3 = []
        while len(ex3) < N:
            batch = list(words)
            random.shuffle(batch)
            ex3 += batch
        ex3 = ex3[:N]
    exercises.append(' '.join(ex3).strip())

    return exercises

# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    random.seed(0)
    os.makedirs(EXERCISES_DIR, exist_ok=True)

    with open(LESSON_WORDS_FILE, 'r', encoding='utf-8') as f:
        lesson_words = json.load(f)

    with open(LESSON_PLAN_FILE, 'r', encoding='utf-8') as f:
        lesson_plan = json.load(f)

    # Iterator over lesson_words — advanced only for non-message entries
    words_iter = iter(lesson_words)

    manifest_lessons   = []
    all_previous_chars = []
    lesson_counter     = 0

    for plan_entry in lesson_plan:
        lesson_counter += 1
        lid = f"{lesson_counter:02d}"

        # ── Message entry ─────────────────────────────────────────────────────
        if 'message' in plan_entry:
            message_text = plan_entry['message']
            ex_id   = f"{lid}-01"
            data    = {
                '_version':         '1.0.0',
                'exercise_type':    'message',
                'combination_mode': True,
                'accuracy_target':  100,
                'text':             message_text,
            }
            ex_file = os.path.join(EXERCISES_DIR, f"{ex_id}.json")
            with open(ex_file, 'w', encoding='utf-8') as f:
                json.dump(data, f, ensure_ascii=False, indent=2)
            manifest_lessons.append({
                'id':               lid,
                'name':             '─',
                'chars':            [],
                'combination_mode': False,
                'exercises':        [ex_id],
            })
            print(f"\nLesson {lid} — [message] {repr(message_text[:50])}")
            continue

        # ── Normal lesson — get from lesson_words ─────────────────────────────
        lesson       = next(words_iter)
        chars        = lesson.get('chars', [])
        combo        = lesson.get('combo', False)
        name         = lesson.get('name', '')
        words        = lesson.get('words', [])
        consonants   = [ch for ch in chars if is_consonant(ch)]

        review_chars = [c for c in all_previous_chars if c not in chars]
        all_chars    = chars + review_chars

        mode_label = 'combination' if combo else 'non-combination'
        print(f"\nLesson {lid} — {name}  [{mode_label}]")

        if combo and consonants:
            word_count = lesson.get('word_count', 0)  # from lesson_words.json
            texts        = make_combo_exercises(consonants, review_chars, words, lesson_id=lesson_counter, has_words=word_count > 0)
            accuracy_map = {1: 100, 2: 90, 3: 80} if word_count > 0 else {1: 100}
        else:
            texts        = make_non_combo_exercises(chars, review_chars, lesson_id=lesson_counter)
            accuracy_map = {1:100, 2:100, 3:100, 4:100, 5:90, 6:80}

        exercise_ids = []
        for i, text in enumerate(texts, 1):
            ex_id           = f"{lid}-{i:02d}"
            accuracy_target = accuracy_map.get(i, 80)
            exercise_type   = {100: 'introduction', 90: 'review', 80: 'practice'}.get(accuracy_target, 'practice')

            data = {
                '_version':         '1.0.0',
                'exercise_type':    exercise_type,
                'combination_mode': combo,
                'accuracy_target':  accuracy_target,
                'text':             text.strip(),
            }
            ex_file = os.path.join(EXERCISES_DIR, f"{ex_id}.json")
            with open(ex_file, 'w', encoding='utf-8') as f:
                json.dump(data, f, ensure_ascii=False, indent=2)
            print(f"  {ex_id}: [{exercise_type}] {repr(text[:60])}{'...' if len(text)>60 else ''}")
            exercise_ids.append(ex_id)

        # Manifest chars: for combo show all uyirmei combinations
        if combo and consonants:
            manifest_chars = []
            for cons in consonants:
                manifest_chars += make_uyirmei_chars(cons)
            manifest_chars += review_chars
        else:
            manifest_chars = all_chars

        manifest_lessons.append({
            'id':               lid,
            'name':             name,
            'chars':            manifest_chars,
            'combination_mode': combo,
            'exercises':        exercise_ids,
        })

        for ch in chars:
            if ch not in all_previous_chars:
                all_previous_chars.append(ch)

    manifest = {
        '_version':     '1.0.0',
        '_description': 'எழுது lesson manifest',
        'lessons':      manifest_lessons,
    }
    with open(LESSONS_FILE, 'w', encoding='utf-8') as f:
        json.dump(manifest, f, ensure_ascii=False, indent=2)

    print(f"\ndata/lessons.json updated — {len(manifest_lessons)} lessons")
    print(f"Exercise files: {EXERCISES_DIR}")
    print("\nDone! ✓")

if __name__ == '__main__':
    main()
